import { useState, useEffect } from 'react';
import {
  Star,
  Heart,
  Briefcase,
  Sparkles,
  Moon,
  Lock,
  Bookmark,
  BookmarkCheck,
  PenLine,
  Share2,
  TrendingUp,

  Gift,
  Globe,
  Shield,
  Flame,
  AlertTriangle,
} from 'lucide-react';
import { Card, Button, Chip, toast } from '../ui';
import { useAuth } from '../../context/AuthContext';
import { useUI } from '../../context/UIContext';
import { supabase } from '../../lib/supabase';
import { getZodiacSign, zodiacData, getElementColor } from '../../utils/zodiac';
import {
  generateDailyHoroscope,
  getPlanetaryTransit,
  getDailyAffirmation,
  getLuckyNumbers
} from '../../data/horoscopes';
import { generateDailyReading } from '../../services/dailyContent';
import { fullDeck } from '../../data/tarotDeck';
import { shareToNative, copyToClipboard } from '../../services/share';
import { awardXP } from '../../services/levelSystem';
import { checkAchievementProgress } from '../../services/achievements';
import { appStorage } from '../../lib/appStorage';

type TimePeriod = 'today' | 'week' | 'month';

interface HoroscopeSectionProps {
  onShowPaywall: (feature: string) => void;
}

const weeklyInsights = [
  'Early week brings clarity in communication. Mid-week favors bold decisions. Weekend calls for rest.',
  'Focus on relationships early in the week. Career matters peak mid-week. Financial review needed by Friday.',
  'Monday starts slow but momentum builds. Wednesday brings unexpected news. Weekend offers romantic possibilities.',
  'Creative energy high at week\'s start. Practical matters demand attention mid-week. Saturday perfect for social events.',
];

const monthlyThemes = [
  'This month emphasizes personal transformation. Career opportunities arise around the 15th. Love life stabilizes by month\'s end.',
  'Financial matters dominate early month. Relationship developments mid-month. Personal growth accelerates in final week.',
  'Health and wellness take center stage. Professional recognition comes unexpectedly. Emotional clarity arrives by the 20th.',
];

export function HoroscopeSection({ onShowPaywall }: HoroscopeSectionProps) {
  const { user, profile, refreshProfile } = useAuth();
  const { setActiveTab } = useUI();
  const [period, setPeriod] = useState<TimePeriod>('today');
  const [isSaved, setIsSaved] = useState(false);
  const [showExtras, setShowExtras] = useState(false);

  const today = new Date().toISOString().split('T')[0];
  const zodiacSign = profile?.birthDate ? getZodiacSign(profile.birthDate) : 'aries';
  const zodiacInfo = zodiacData[zodiacSign];
  const horoscope = generateDailyHoroscope(zodiacSign, today);
  const dailyReading = generateDailyReading({ sign: zodiacSign, date: today });
  const planetaryTransit = getPlanetaryTransit(today);
  const affirmation = getDailyAffirmation(zodiacSign, today);
  const luckyNumbers = getLuckyNumbers(today, 6);

  useEffect(() => {
    if (!user) return;
    const key = `arcana_horoscope_xp_${today}`;
    appStorage.get(key).then((val) => {
      if (val) return;
      appStorage.set(key, '1');
      awardXP(user.id, 'horoscope_viewed').then(() => refreshProfile());
    });
    checkAchievementProgress(user.id, 'horoscope_viewed');
  }, [user, today]);

  const getDailyTarotCard = () => {
    const dateNum = new Date(today).getTime();
    const signNum = zodiacSign.charCodeAt(0);
    const index = (dateNum + signNum) % fullDeck.length;
    return fullDeck[index];
  };

  const tarotCard = getDailyTarotCard();

  const weekIndex = Math.floor(new Date().getTime() / (1000 * 60 * 60 * 24 * 7)) % weeklyInsights.length;
  const monthIndex = new Date().getMonth() % monthlyThemes.length;

  const handleSave = async () => {
    if (!user) return;

    const { error } = await supabase.from('saved_highlights').insert({
      user_id: user.id,
      date: today,
      highlight_type: 'horoscope',
      content: { period, horoscope, zodiacSign },
    });

    if (error) {
      toast('Failed to save', 'error');
    } else {
      setIsSaved(true);
      toast('Horoscope saved', 'success');
    }
  };

  const handleJournalPrompt = () => {
    setActiveTab('journal');
  };

  const handleMonthView = () => {
    if (!profile?.isPremium) {
      onShowPaywall('Monthly Horoscope');
      return;
    }
    setPeriod('month');
  };

  const handleShare = async () => {
    const shareText = `${zodiacInfo.name} Horoscope for Today\n\n${horoscope.general}\n\nAffirmation: ${affirmation}\n\nGenerated by Arcana ✨`;
    const success = await shareToNative('My Daily Horoscope', shareText);
    if (success) {
      toast('Shared successfully', 'success');
    } else {
      const copied = await copyToClipboard(shareText);
      if (copied) {
        toast('Copied to clipboard', 'success');
      } else {
        toast('Unable to share', 'error');
      }
    }
  };

  return (
    <div className="space-y-6">
      <div className="relative -mx-4 px-4">
        <div
          className="flex gap-2 overflow-x-auto pb-1 snap-x snap-mandatory scroll-smooth"
          style={{
            WebkitOverflowScrolling: 'touch',
            scrollbarWidth: 'none',
            msOverflowStyle: 'none'
          }}
        >
          <Chip selected={period === 'today'} onClick={() => setPeriod('today')}>
            Today
          </Chip>
          <Chip selected={period === 'week'} onClick={() => setPeriod('week')}>
            This Week
          </Chip>
          <Chip
            selected={period === 'month'}
            onClick={handleMonthView}
          >
            {!profile?.isPremium && <Lock className="w-3 h-3 mr-1" />}
            This Month
          </Chip>
        </div>
      </div>

      <Card variant="glow" padding="lg">
        <div className="flex items-center gap-4 mb-6">
          <div className={`w-16 h-16 rounded-2xl bg-mystic-800 flex items-center justify-center text-3xl ${getElementColor(zodiacInfo.element)}`}>
            {zodiacInfo.symbol}
          </div>
          <div className="flex-1">
            <h2 className="font-display text-2xl text-gold">{zodiacInfo.name}</h2>
            <p className="text-mystic-400 text-sm">{zodiacInfo.dateRange}</p>
          </div>
          <button
            onClick={handleSave}
            className="p-2 rounded-full hover:bg-mystic-800 transition-colors active:scale-90"
          >
            {isSaved ? (
              <BookmarkCheck className="w-5 h-5 text-gold" />
            ) : (
              <Bookmark className="w-5 h-5 text-mystic-400" />
            )}
          </button>
        </div>

        {period === 'today' && (
          <div className="space-y-6">
            <div className="flex items-center gap-2 mb-4">
              <p className="text-xs text-mystic-500 uppercase tracking-wider">Energy Score</p>
              <div className="flex-1 h-2 bg-mystic-800 rounded-full overflow-hidden">
                <div
                  className="h-full bg-gradient-to-r from-gold/60 to-gold rounded-full transition-all"
                  style={{ width: `${(horoscope.energy / 5) * 100}%` }}
                />
              </div>
              <span className="text-sm text-gold font-medium">{horoscope.energy}/5</span>
            </div>

            <div>
              <h3 className="text-sm font-medium text-mystic-400 uppercase tracking-wide mb-2">General</h3>
              <p className="text-mystic-200 leading-relaxed">{horoscope.general}</p>
            </div>

            <div className="grid grid-cols-1 gap-4">
              <div className="flex items-start gap-3 p-3 bg-mystic-800/50 rounded-xl">
                <Heart className="w-5 h-5 text-cosmic-rose flex-shrink-0 mt-0.5" />
                <div>
                  <h4 className="text-sm font-medium text-mystic-200 mb-1">Love</h4>
                  <p className="text-sm text-mystic-400 leading-relaxed">{horoscope.love}</p>
                </div>
              </div>

              <div className="flex items-start gap-3 p-3 bg-mystic-800/50 rounded-xl">
                <Briefcase className="w-5 h-5 text-cosmic-blue flex-shrink-0 mt-0.5" />
                <div>
                  <h4 className="text-sm font-medium text-mystic-200 mb-1">Work</h4>
                  <p className="text-sm text-mystic-400 leading-relaxed">{horoscope.career}</p>
                </div>
              </div>

              <div className="flex items-start gap-3 p-3 bg-mystic-800/50 rounded-xl">
                <Sparkles className="w-5 h-5 text-gold flex-shrink-0 mt-0.5" />
                <div>
                  <h4 className="text-sm font-medium text-mystic-200 mb-1">Mood</h4>
                  <p className="text-sm text-mystic-400 leading-relaxed">
                    Your energy levels indicate a {horoscope.energy >= 4 ? 'highly productive' : horoscope.energy >= 3 ? 'balanced' : 'reflective'} day ahead.
                  </p>
                </div>
              </div>
            </div>

            <div className="pt-4 border-t border-mystic-700 space-y-4">
              <div>
                <h4 className="text-sm font-medium text-mystic-400 uppercase tracking-wide mb-3">Lucky Focus</h4>
                <div className="grid grid-cols-3 gap-3">
                  <div className="text-center p-3 bg-mystic-800/30 rounded-xl">
                    <p className="text-xs text-mystic-500 mb-1">Color</p>
                    <p className="text-sm text-mystic-200 font-medium">{horoscope.luckyColor}</p>
                  </div>
                  <div className="text-center p-3 bg-mystic-800/30 rounded-xl">
                    <p className="text-xs text-mystic-500 mb-1">Number</p>
                    <p className="text-lg font-display text-gold">{horoscope.luckyNumber}</p>
                  </div>
                  <div className="text-center p-3 bg-mystic-800/30 rounded-xl">
                    <p className="text-xs text-mystic-500 mb-1">Vibe</p>
                    <p className="text-sm text-mystic-200 font-medium">
                      {horoscope.energy >= 4 ? 'Expansive' : horoscope.energy >= 3 ? 'Steady' : 'Introspective'}
                    </p>
                  </div>
                </div>
              </div>

              <div className="flex items-start gap-3 p-4 bg-mystic-800/30 rounded-xl">
                <Sparkles className="w-5 h-5 text-gold flex-shrink-0 mt-0.5" />
                <div className="flex-1">
                  <h4 className="text-sm font-medium text-mystic-200 mb-1">Today's Mood</h4>
                  <p className="text-sm text-mystic-400">{dailyReading.mood}</p>
                </div>
              </div>

              <div className="flex items-start gap-3 p-4 bg-mystic-800/30 rounded-xl">
                <Shield className="w-5 h-5 text-orange-400 flex-shrink-0 mt-0.5" />
                <div className="flex-1">
                  <h4 className="text-sm font-medium text-mystic-200 mb-1">Shadow Insight</h4>
                  <p className="text-sm text-mystic-400">{dailyReading.shadow}</p>
                </div>
              </div>

              <div className="flex items-start gap-3 p-4 bg-orange-900/10 border border-orange-500/20 rounded-xl">
                <AlertTriangle className="w-5 h-5 text-amber-400 flex-shrink-0 mt-0.5" />
                <div className="flex-1">
                  <h4 className="text-sm font-medium text-mystic-200 mb-1">Caution</h4>
                  <p className="text-xs text-mystic-400">{dailyReading.caution}</p>
                </div>
              </div>

              <div className="flex items-start gap-3 p-4 bg-gradient-to-r from-gold/10 to-cosmic-blue/10 border border-gold/20 rounded-xl">
                <Globe className="w-5 h-5 text-gold flex-shrink-0 mt-0.5" />
                <div className="flex-1">
                  <h4 className="text-sm font-medium text-mystic-200 mb-1">Planetary Transit</h4>
                  <p className="text-xs text-mystic-400">{planetaryTransit}</p>
                </div>
              </div>

              <div className="flex items-start gap-3 p-4 bg-gradient-to-r from-cosmic-rose/10 to-gold/10 border border-cosmic-rose/20 rounded-xl">
                <Sparkles className="w-5 h-5 text-cosmic-rose flex-shrink-0 mt-0.5" />
                <div className="flex-1">
                  <h4 className="text-sm font-medium text-mystic-200 mb-1">Daily Affirmation</h4>
                  <p className="text-sm text-mystic-300 italic">&ldquo;{affirmation}&rdquo;</p>
                </div>
              </div>

              <div className="flex items-start gap-3 p-4 bg-mystic-800/30 rounded-xl">
                <Sparkles className="w-5 h-5 text-gold flex-shrink-0 mt-0.5" />
                <div className="flex-1">
                  <h4 className="text-sm font-medium text-mystic-200 mb-2">Card of the Day</h4>
                  <div className="flex items-center gap-3">
                    <div className="text-2xl">{tarotCard.arcana === 'major' ? '🌟' : tarotCard.suit === 'wands' ? '🔥' : tarotCard.suit === 'cups' ? '💧' : tarotCard.suit === 'swords' ? '⚔️' : '🌍'}</div>
                    <div>
                      <p className="text-sm text-gold font-medium">{tarotCard.name}</p>
                      <p className="text-xs text-mystic-400 mt-0.5">{tarotCard.keywords.slice(0, 3).join(', ')}</p>
                    </div>
                  </div>
                </div>
              </div>

              {showExtras && (
                <>
                  <div className="flex items-start gap-3 p-4 bg-gold/5 border border-gold/20 rounded-xl">
                    <Gift className="w-5 h-5 text-gold flex-shrink-0 mt-0.5" />
                    <div className="flex-1">
                      <h4 className="text-sm font-medium text-mystic-200 mb-2">Lucky Numbers</h4>
                      <div className="flex flex-wrap gap-2">
                        {luckyNumbers.map((num, i) => (
                          <div
                            key={i}
                            className="w-10 h-10 rounded-full bg-gold/20 border border-gold/30 flex items-center justify-center"
                          >
                            <span className="text-sm font-bold text-gold">{num}</span>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>

                  <div className="flex items-start gap-3 p-4 bg-gradient-to-r from-gold/5 to-mystic-800/30 border border-gold/10 rounded-xl">
                    <Flame className="w-5 h-5 text-gold flex-shrink-0 mt-0.5" />
                    <div className="flex-1">
                      <h4 className="text-sm font-medium text-mystic-200 mb-1">Mini Ritual</h4>
                      <p className="text-xs text-mystic-400 leading-relaxed">{dailyReading.miniRitual}</p>
                    </div>
                  </div>

                  <div className="flex items-start gap-3 p-4 bg-mystic-800/30 rounded-xl">
                    <TrendingUp className="w-5 h-5 text-emerald-400 flex-shrink-0 mt-0.5" />
                    <div className="flex-1">
                      <h4 className="text-sm font-medium text-mystic-200 mb-1">Action Step</h4>
                      <p className="text-xs text-mystic-400 leading-relaxed">{dailyReading.actionStep}</p>
                    </div>
                  </div>
                </>
              )}

              <button
                onClick={() => setShowExtras(!showExtras)}
                className="w-full text-sm text-mystic-400 hover:text-gold transition-colors"
              >
                {showExtras ? 'Show Less' : 'Show More Insights'}
              </button>
            </div>
          </div>
        )}

        {period === 'week' && (
          <div className="space-y-6">
            <div>
              <h3 className="text-sm font-medium text-mystic-400 uppercase tracking-wide mb-2">Weekly Overview</h3>
              <p className="text-mystic-200 leading-relaxed">{weeklyInsights[weekIndex]}</p>
            </div>

            <div className="grid grid-cols-7 gap-1">
              {['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((day, i) => {
                const daySeed = new Date(today).getTime() + zodiacSign.charCodeAt(0) + i * 7919;
                const energy = (daySeed % 5) + 1;
                return (
                  <div key={i} className="text-center">
                    <p className="text-xs text-mystic-500 mb-1">{day}</p>
                    <div className="h-12 bg-mystic-800/50 rounded flex items-end justify-center pb-1">
                      <div
                        className="w-4 bg-gradient-to-t from-gold/60 to-gold rounded-t"
                        style={{ height: `${(energy / 5) * 100}%` }}
                      />
                    </div>
                  </div>
                );
              })}
            </div>

            <div className="grid grid-cols-3 gap-3 pt-4 border-t border-mystic-700">
              <div className="text-center">
                <Heart className="w-5 h-5 text-cosmic-rose mx-auto mb-1" />
                <p className="text-xs text-mystic-400">Love Peak</p>
                <p className="text-sm text-mystic-200">Wednesday</p>
              </div>
              <div className="text-center">
                <Briefcase className="w-5 h-5 text-cosmic-blue mx-auto mb-1" />
                <p className="text-xs text-mystic-400">Career Peak</p>
                <p className="text-sm text-mystic-200">Thursday</p>
              </div>
              <div className="text-center">
                <Star className="w-5 h-5 text-gold mx-auto mb-1" />
                <p className="text-xs text-mystic-400">Best Day</p>
                <p className="text-sm text-mystic-200">Friday</p>
              </div>
            </div>
          </div>
        )}

        {period === 'month' && (
          <div className="space-y-6">
            <div>
              <h3 className="text-sm font-medium text-mystic-400 uppercase tracking-wide mb-2">Monthly Theme</h3>
              <p className="text-mystic-200 leading-relaxed">{monthlyThemes[monthIndex]}</p>
            </div>

            <div className="space-y-3">
              <div className="flex items-center gap-3 p-3 bg-mystic-800/50 rounded-xl">
                <Moon className="w-5 h-5 text-mystic-300" />
                <div>
                  <p className="text-xs text-mystic-500">Moon Phase Influence</p>
                  <p className="text-sm text-mystic-200">New Moon on the 12th amplifies new beginnings</p>
                </div>
              </div>

              <div className="flex items-center gap-3 p-3 bg-mystic-800/50 rounded-xl">
                <Star className="w-5 h-5 text-gold" />
                <div>
                  <p className="text-xs text-mystic-500">Key Dates</p>
                  <p className="text-sm text-mystic-200">7th, 15th, 23rd - High energy days</p>
                </div>
              </div>
            </div>
          </div>
        )}
      </Card>

      <div className="grid grid-cols-3 gap-2">
        <Button variant="outline" onClick={handleSave} className="min-h-[44px]">
          {isSaved ? <BookmarkCheck className="w-4 h-4" /> : <Bookmark className="w-4 h-4" />}
        </Button>
        <Button variant="gold" onClick={handleJournalPrompt} className="min-h-[44px]">
          <PenLine className="w-4 h-4" />
          Journal
        </Button>
        <Button variant="outline" onClick={handleShare} className="min-h-[44px]">
          <Share2 className="w-4 h-4" />
        </Button>
      </div>

      {!profile?.isPremium && (
        <Card
          padding="md"
          interactive
          onClick={() => onShowPaywall('Birth Chart Analysis')}
          className="flex items-center justify-between active:scale-[0.98] transition-transform"
        >
          <div className="flex items-center gap-3">
            <Lock className="w-5 h-5 text-mystic-500" />
            <div>
              <h3 className="font-medium text-mystic-200">Birth Chart Analysis</h3>
              <p className="text-sm text-mystic-400">Personalized transit notes</p>
            </div>
          </div>
          <Button variant="gold" size="sm">Upgrade</Button>
        </Card>
      )}
    </div>
  );
}
