// GENERATED by scratchpad/p7-B5-gen-playing.mjs from src/data/cartomancy/cards.en.ts
// (quickMeaning of the 52 suited cards; Jokers excluded — the quick reading has
// no settings surface). Do not edit by hand: fix the corpus and re-run the
// generator. Edge functions cannot import src/, hence this copy.

export type PlayingSuit = "hearts" | "clubs" | "diamonds" | "spades";

export interface PlayingQuickCard {
  /** 100..151 — matches src/data/cartomancy ids (100 + suitIndex * 13 + rankIndex). */
  id: number;
  /** URL slug, never localized, e.g. "nine-of-hearts". */
  slug: string;
  name: string;
  suit: PlayingSuit;
  color: "red" | "black";
  /** One line, the card's quickMeaning from the reviewed corpus. */
  meaning: string;
}

export const PLAYING: PlayingQuickCard[] = [
  { id: 100, slug: "ace-of-hearts", name: "Ace of Hearts", suit: "hearts", color: "red", meaning: "A new warmth has arrived. Welcome it before you decide what it means." },
  { id: 101, slug: "two-of-hearts", name: "Two of Hearts", suit: "hearts", color: "red", meaning: "Something mutual is forming. Meet it halfway." },
  { id: 102, slug: "three-of-hearts", name: "Three of Hearts", suit: "hearts", color: "red", meaning: "Shared joy is near. Make room for company." },
  { id: 103, slug: "four-of-hearts", name: "Four of Hearts", suit: "hearts", color: "red", meaning: "A pause in the heart. Use it to decide, not to drift." },
  { id: 104, slug: "five-of-hearts", name: "Five of Hearts", suit: "hearts", color: "red", meaning: "A bond is being tested. Honesty will do more than reassurance." },
  { id: 105, slug: "six-of-hearts", name: "Six of Hearts", suit: "hearts", color: "red", meaning: "Something faithful is still here. Let it count." },
  { id: 106, slug: "seven-of-hearts", name: "Seven of Hearts", suit: "hearts", color: "red", meaning: "Feeling is running ahead of fact. Let them catch up to each other." },
  { id: 107, slug: "eight-of-hearts", name: "Eight of Hearts", suit: "hearts", color: "red", meaning: "Company is calling. Go, and stay only while it feeds you." },
  { id: 108, slug: "nine-of-hearts", name: "Nine of Hearts", suit: "hearts", color: "red", meaning: "The wish card. What you have been hoping for is closer than it feels." },
  { id: 109, slug: "ten-of-hearts", name: "Ten of Hearts", suit: "hearts", color: "red", meaning: "Warmth that lasts. Something built with love is holding." },
  { id: 110, slug: "jack-of-hearts", name: "Jack of Hearts", suit: "hearts", color: "red", meaning: "A loyal, affectionate presence. Let yourself be loved simply." },
  { id: 111, slug: "queen-of-hearts", name: "Queen of Hearts", suit: "hearts", color: "red", meaning: "A caring presence is near. Let yourself be held." },
  { id: 112, slug: "king-of-hearts", name: "King of Hearts", suit: "hearts", color: "red", meaning: "A generous, steady presence. Trust the help that is offered." },
  { id: 113, slug: "ace-of-clubs", name: "Ace of Clubs", suit: "clubs", color: "black", meaning: "A spark for work or growth. Act on it while it is warm." },
  { id: 114, slug: "two-of-clubs", name: "Two of Clubs", suit: "clubs", color: "black", meaning: "A partnership is forming. Set the terms kindly and clearly." },
  { id: 115, slug: "three-of-clubs", name: "Three of Clubs", suit: "clubs", color: "black", meaning: "Growth is meeting resistance. Find the gap, not the fight." },
  { id: 116, slug: "four-of-clubs", name: "Four of Clubs", suit: "clubs", color: "black", meaning: "The ground is ready. Do the real work, not the shortcut." },
  { id: 117, slug: "five-of-clubs", name: "Five of Clubs", suit: "clubs", color: "black", meaning: "Good company and good health. Let the circle widen." },
  { id: 118, slug: "six-of-clubs", name: "Six of Clubs", suit: "clubs", color: "black", meaning: "A path is opening and you do not have to walk it alone." },
  { id: 119, slug: "seven-of-clubs", name: "Seven of Clubs", suit: "clubs", color: "black", meaning: "Worry is louder than the problem. Do the next small thing." },
  { id: 120, slug: "eight-of-clubs", name: "Eight of Clubs", suit: "clubs", color: "black", meaning: "A demanding stretch. Set a finish line before you start." },
  { id: 121, slug: "nine-of-clubs", name: "Nine of Clubs", suit: "clubs", color: "black", meaning: "A harvest from your effort. Gather it and share it." },
  { id: 122, slug: "ten-of-clubs", name: "Ten of Clubs", suit: "clubs", color: "black", meaning: "Work completes. Let success be restful as well as busy." },
  { id: 123, slug: "jack-of-clubs", name: "Jack of Clubs", suit: "clubs", color: "black", meaning: "A trusted friend is close. Lean on them, and let them lean back." },
  { id: 124, slug: "queen-of-clubs", name: "Queen of Clubs", suit: "clubs", color: "black", meaning: "Capable support, or your own capability. Use it." },
  { id: 125, slug: "king-of-clubs", name: "King of Clubs", suit: "clubs", color: "black", meaning: "Trusted authority is near. Take the advice, keep the decision." },
  { id: 126, slug: "ace-of-diamonds", name: "Ace of Diamonds", suit: "diamonds", color: "red", meaning: "News, likely about money, is on its way. Be ready to act." },
  { id: 127, slug: "two-of-diamonds", name: "Two of Diamonds", suit: "diamonds", color: "red", meaning: "An exchange is being made. Make sure it is fair both ways." },
  { id: 128, slug: "three-of-diamonds", name: "Three of Diamonds", suit: "diamonds", color: "red", meaning: "A document or a gift with terms. Tact decides how it goes." },
  { id: 129, slug: "four-of-diamonds", name: "Four of Diamonds", suit: "diamonds", color: "red", meaning: "Steady your resources. Wisdom from an elder helps." },
  { id: 130, slug: "five-of-diamonds", name: "Five of Diamonds", suit: "diamonds", color: "red", meaning: "A change for the better, helped by others. Pass it on." },
  { id: 131, slug: "six-of-diamonds", name: "Six of Diamonds", suit: "diamonds", color: "red", meaning: "Money and feeling are tangled. Untangle them gently and soon." },
  { id: 132, slug: "seven-of-diamonds", name: "Seven of Diamonds", suit: "diamonds", color: "red", meaning: "Something about money does not add up. Check it kindly and firmly." },
  { id: 133, slug: "eight-of-diamonds", name: "Eight of Diamonds", suit: "diamonds", color: "red", meaning: "A change at work, and talk around it. Keep moving." },
  { id: 134, slug: "nine-of-diamonds", name: "Nine of Diamonds", suit: "diamonds", color: "red", meaning: "Movement and opportunity. Point the restlessness somewhere." },
  { id: 135, slug: "ten-of-diamonds", name: "Ten of Diamonds", suit: "diamonds", color: "red", meaning: "Prosperity arrives. Decide what it is for." },
  { id: 136, slug: "jack-of-diamonds", name: "Jack of Diamonds", suit: "diamonds", color: "red", meaning: "Charm and quick news. Check what you are told." },
  { id: 137, slug: "queen-of-diamonds", name: "Queen of Diamonds", suit: "diamonds", color: "red", meaning: "A connector is near. Use the network, guard your words." },
  { id: 138, slug: "king-of-diamonds", name: "King of Diamonds", suit: "diamonds", color: "red", meaning: "A person of means and authority. Deal as an equal." },
  { id: 139, slug: "ace-of-spades", name: "Ace of Spades", suit: "spades", color: "black", meaning: "An ending with weight. Let it be complete." },
  { id: 140, slug: "two-of-spades", name: "Two of Spades", suit: "spades", color: "black", meaning: "A separation or a stalemate. Someone has to move; it may be you." },
  { id: 141, slug: "three-of-spades", name: "Three of Spades", suit: "spades", color: "black", meaning: "A quarrel, perhaps with a third party in it. Fight only what is yours." },
  { id: 142, slug: "four-of-spades", name: "Four of Spades", suit: "spades", color: "black", meaning: "Stuck for now. Rest, and tend the small things." },
  { id: 143, slug: "five-of-spades", name: "Five of Spades", suit: "spades", color: "black", meaning: "Strain and opposition, for now. Guard your health first." },
  { id: 144, slug: "six-of-spades", name: "Six of Spades", suit: "spades", color: "black", meaning: "A way through, step by step. Avoid the easy vice." },
  { id: 145, slug: "seven-of-spades", name: "Seven of Spades", suit: "spades", color: "black", meaning: "Sorrow, and the strength that comes after it. Be gentle with yourself." },
  { id: 146, slug: "eight-of-spades", name: "Eight of Spades", suit: "spades", color: "black", meaning: "Words are going wrong. Speak plainly before the silence does." },
  { id: 147, slug: "nine-of-spades", name: "Nine of Spades", suit: "spades", color: "black", meaning: "A low point, and fear with it. Reach out; this passes." },
  { id: 148, slug: "ten-of-spades", name: "Ten of Spades", suit: "spades", color: "black", meaning: "A heavy cycle ends. Put the burden down." },
  { id: 149, slug: "jack-of-spades", name: "Jack of Spades", suit: "spades", color: "black", meaning: "Someone or something not yet proven. Watch, then decide." },
  { id: 150, slug: "queen-of-spades", name: "Queen of Spades", suit: "spades", color: "black", meaning: "Strength forged by loss. Speak truth with care." },
  { id: 151, slug: "king-of-spades", name: "King of Spades", suit: "spades", color: "black", meaning: "A formidable authority. Prepare, and hold your ground." },
];
