#!/usr/bin/env node
/**
 * Build-time image optimization pipeline.
 * Generates thumbnail (150px), full (400px), and LQIP (20px base64) variants
 * for every bundled tarot card image.
 *
 * Usage:  node scripts/optimize-images.mjs
 * Output: public/bundled-cards/{thumb,full}/ mirrors the source structure
 *         src/config/lqip-map.ts  — base64 placeholders keyed by card slug
 */

import sharp from 'sharp';
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync, existsSync } from 'fs';
import { join, relative, basename, dirname, extname } from 'path';

const SRC_DIR = 'public/bundled-cards';
const THUMB_W = 150;
const FULL_W = 400;
const LQIP_W = 20;

/** Recursively find all .webp files */
function findWebp(dir) {
  const results = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      // Skip output dirs
      if (entry === 'thumb' || entry === 'full' || entry === 'placeholders') continue;
      results.push(...findWebp(full));
    } else if (extname(entry) === '.webp') {
      results.push(full);
    }
  }
  return results;
}

async function processImage(srcPath) {
  const rel = relative(SRC_DIR, srcPath);
  const thumbOut = join(SRC_DIR, 'thumb', rel);
  const fullOut = join(SRC_DIR, 'full', rel);

  mkdirSync(dirname(thumbOut), { recursive: true });
  mkdirSync(dirname(fullOut), { recursive: true });

  const buf = readFileSync(srcPath);

  // Thumbnail — 150px wide, quality 70
  await sharp(buf)
    .resize(THUMB_W, null, { withoutEnlargement: true })
    .webp({ quality: 70 })
    .toFile(thumbOut);

  // Full — 400px wide, quality 80
  await sharp(buf)
    .resize(FULL_W, null, { withoutEnlargement: true })
    .webp({ quality: 80 })
    .toFile(fullOut);

  // LQIP — tiny 20px base64
  const lqipBuf = await sharp(buf)
    .resize(LQIP_W, null, { withoutEnlargement: true })
    .webp({ quality: 30 })
    .toBuffer();

  const slug = basename(srcPath, '.webp');
  const base64 = `data:image/webp;base64,${lqipBuf.toString('base64')}`;

  return { slug, base64, thumbSize: (await sharp(buf).resize(THUMB_W).webp({ quality: 70 }).toBuffer()).length };
}

async function main() {
  const files = findWebp(SRC_DIR);
  console.log(`Found ${files.length} card images to optimize.`);

  const lqipEntries = [];
  let totalThumb = 0;
  let totalFull = 0;

  for (const file of files) {
    const { slug, base64, thumbSize } = await processImage(file);
    lqipEntries.push({ slug, base64 });
    totalThumb += thumbSize;
    process.stdout.write('.');
  }

  console.log(`\nDone! Generated thumb + full + LQIP for ${files.length} images.`);

  // Generate LQIP map TypeScript file
  const mapEntries = lqipEntries
    .sort((a, b) => a.slug.localeCompare(b.slug))
    .map(({ slug, base64 }) => `  '${slug}': '${base64}',`)
    .join('\n');

  const tsContent = `// Auto-generated by scripts/optimize-images.mjs — do not edit
export const LQIP_MAP: Record<string, string> = {
${mapEntries}
};

export function getLqip(slug: string): string {
  return LQIP_MAP[slug] || '';
}
`;

  writeFileSync('src/config/lqip-map.ts', tsContent);
  console.log(`Wrote src/config/lqip-map.ts with ${lqipEntries.length} LQIP entries.`);

  // Summary
  const thumbDir = join(SRC_DIR, 'thumb');
  const fullDir = join(SRC_DIR, 'full');
  console.log(`\nOutput directories:`);
  console.log(`  ${thumbDir}/  (${THUMB_W}px thumbnails for grids)`);
  console.log(`  ${fullDir}/  (${FULL_W}px full-size for detail views)`);
}

main().catch(err => { console.error(err); process.exit(1); });
