// GENERATED by scratchpad/p7-F4-gen-cards.mjs from p7-cartomancy-content.json
// (corpus version 1, 2026-10-02). Do not edit by hand: fix the
// corpus and run the generator. The system tables: suits, number keys, timing, and the combination tables the reader functions in combinations.ts run on.
import type {
  CartoTiming,
  NeighborRule,
  PlayingSuitInfo,
  RankKey,
  SameRankCombination,
} from '../../types/cartomancy';

/** The tradition this deck is read in, stated once. */
export const CARTO_SYSTEM = {
  name: "English and American 52-card tradition",
  deck: "52 cards; two Jokers optional (off by default)",
  reversals: "off by default; user setting; every card carries a reversed meaning for when it is on",
  significator: "optional, off by default; King or Queen of Hearts for the reader, or any court card, or the Red Joker",
  divergenceNote: "The French 32-card (piquet) lineage often gives Clubs (trefle) money and luck and Diamonds (carreau) news and journeys, and drops the Twos through Sixes. Arcana reads all 52 with Diamonds as money and Clubs as work, and notes the French sense on cards where it adds something (Ace of Diamonds, Six of Diamonds, Nine of Diamonds).",
} as const;

export const CARTO_SUITS: PlayingSuitInfo[] = [
  {
    id: "hearts",
    name: "Hearts",
    color: "red",
    domain: "Feeling: love, friendship, family, the home",
    verb: "feeling",
    season: "summer",
    speed: "weeks",
    yesNo: "yes, in matters of the heart",
    legacyComplexion: "fair or medium coloring",
    keywords: ["love", "emotion", "home", "family", "friendship"],
  },
  {
    id: "clubs",
    name: "Clubs",
    color: "black",
    domain: "Doing: work, growth, effort, ambition, alliances",
    verb: "doing",
    season: "autumn",
    speed: "days",
    yesNo: "no, because work comes first",
    legacyComplexion: "dark hair",
    keywords: ["work", "growth", "effort", "friendship", "ambition"],
  },
  {
    id: "diamonds",
    name: "Diamonds",
    color: "red",
    domain: "Having: money, property, deals, documents, news",
    verb: "having",
    season: "spring",
    speed: "hours or days",
    yesNo: "yes, in money and practical matters",
    legacyComplexion: "very fair or red hair",
    keywords: ["money", "material", "news", "deals", "documents"],
  },
  {
    id: "spades",
    name: "Spades",
    color: "black",
    domain: "Facing: difficulty, endings, truth, what must be dealt with",
    verb: "facing",
    season: "winter",
    speed: "weeks to months",
    yesNo: "no, because something must end or be faced",
    legacyComplexion: "dark or black hair",
    keywords: ["challenge", "truth", "endings", "conflict", "effort"],
  },
];

export const CARTO_NUMBERS: RankKey[] = [
  { rank: "ace", value: 1, key: "Beginnings; a single thing arriving; a message or a seed" },
  { rank: "2", value: 2, key: "Pairs; exchange; agreement or standoff" },
  { rank: "3", value: 3, key: "Growth; wishes; company; a third party" },
  { rank: "4", value: 4, key: "Stability; stillness; a decision pending" },
  { rank: "5", value: 5, key: "Groups; disturbance; the body; gains and losses" },
  { rank: "6", value: 6, key: "Paths; help on the way; the road chosen" },
  { rank: "7", value: 7, key: "The suit distilled; intensity; trouble or mastery" },
  { rank: "8", value: 8, key: "Talk; movement; the social world" },
  {
    rank: "9",
    value: 9,
    key: "Expansion; fulfillment or its opposite; the wish, the harvest, the journey, the low",
  },
  {
    rank: "10",
    value: 10,
    key: "Completion; the full house, the finished work, the treasure, the burden",
  },
  { rank: "jack", value: 11, key: "The young; messengers; friends and peers" },
  {
    rank: "queen",
    value: 12,
    key: "Mature capability; nurturers, organizers, connectors, survivors",
  },
  { rank: "king", value: 13, key: "Authority; providers, advisers, magnates, officials" },
];

export const CARTO_TIMING: CartoTiming = {
  seasons: { diamonds: "spring", hearts: "summer", clubs: "autumn", spades: "winter" },
  speeds: { diamonds: "hours or days", clubs: "days", hearts: "weeks", spades: "weeks to months" },
  numberIsCount: true,
  courtCards: "depends on the person named",
  method: "Lay three to five cards; the suits set the unit, the number the count; the last card weighs most; beyond a year, ask instead whether it happens at all.",
};

/** Red leans yes, black leans no. */
export const YES_NO_COLORS = { red: "yes", black: "no" } as const;

/** Two, three or four of a rank on the table. */
export const SAME_RANK_COMBINATIONS: SameRankCombination[] = [
  { rank: "ace", count: 4, meaning: "A major turning point; everything begins again." },
  { rank: "ace", count: 3, meaning: "Good news; several beginnings at once." },
  { rank: "ace", count: 2, meaning: "A pairing or a partnership forming." },
  { rank: "king", count: 4, meaning: "Recognition; success among the powerful." },
  { rank: "king", count: 3, meaning: "A consultation; a meeting of authorities." },
  {
    rank: "king",
    count: 2,
    meaning: "A business partnership or a rivalry between two men of standing.",
  },
  { rank: "queen", count: 4, meaning: "A gathering; a great deal of talk." },
  { rank: "queen", count: 3, meaning: "Visits, gossip and company." },
  {
    rank: "queen",
    count: 2,
    meaning: "A friendship between women, or a confidence shared.",
  },
  { rank: "jack", count: 4, meaning: "A noisy crowd; a quarrel among young people." },
  { rank: "jack", count: 3, meaning: "False friends; disputes." },
  { rank: "jack", count: 2, meaning: "A conversation between peers; news exchanged." },
  { rank: "10", count: 4, meaning: "A completion; a great success or a great change." },
  { rank: "10", count: 3, meaning: "A change of circumstances." },
  { rank: "9", count: 4, meaning: "A surprise; an unexpected turn." },
  { rank: "9", count: 3, meaning: "Success after effort." },
  { rank: "8", count: 4, meaning: "A journey or a change of place." },
  { rank: "8", count: 3, meaning: "News; much talk." },
  { rank: "7", count: 4, meaning: "Intrigue; many small troubles." },
  { rank: "7", count: 3, meaning: "Doubt; a decision put off." },
  { rank: "7", count: 2, meaning: "A disagreement; mutual mistrust." },
];

/** What two cards side by side say that neither says alone. */
export const NEIGHBOR_RULES: NeighborRule[] = [
  {
    id: "wish-delayed",
    when: "nine-of-hearts adjacent to any spade",
    meaning: "The wish is favored with a delay or a price, named by the spade.",
  },
  {
    id: "wish-shape",
    when: "nine-of-hearts present",
    meaning: "The card to its right describes the wish; the card to its left what it asks of you.",
  },
  {
    id: "ending-touch",
    when: "ace-of-spades adjacent to any card",
    meaning: "That card's matter is ending or being decided finally.",
  },
  {
    id: "heart-softens",
    when: "any heart adjacent to any spade",
    meaning: "The difficulty is softened by care; the trouble is real but held.",
  },
  {
    id: "earned-money",
    when: "any club adjacent to any diamond",
    meaning: "Money earned rather than received; effort turning into means.",
  },
  {
    id: "seven-intensifies",
    when: "any seven adjacent to any card",
    meaning: "That neighbor is intensified; read it more strongly.",
  },
  {
    id: "court-centered",
    when: "a court card between two cards of its own suit",
    meaning: "That person is central to the whole matter.",
  },
  {
    id: "royal-couple",
    when: "a king and a queen of the same suit together",
    meaning: "A couple, or parents, or two people who run things together.",
  },
  {
    id: "suit-majority",
    when: "a majority of one suit across the table",
    meaning: "The reading's subject, whatever was asked; the minority suit is what is neglected.",
  },
  {
    id: "color-majority",
    when: "a majority of one color across the table",
    meaning: "The reading's mood: red for ease and warmth, black for effort and care.",
  },
];
