/*
  # Enhance Wands Suit Card Descriptions

  1. Updates
    - Updates all 14 Wands cards (Ace through King) with comprehensive descriptions
    - Adds detailed upright and reversed meanings
    - Includes visual descriptions of card imagery
    - Provides love and career specific meanings
    - Adds reflection prompts for self-discovery
  
  2. Cards Enhanced
    - Ace of Wands: Creative spark and new beginnings
    - Two of Wands: Planning and future vision
    - Three of Wands: Expansion and foresight
    - Four of Wands: Celebration and homecoming
    - Five of Wands: Competition and conflict
    - Six of Wands: Victory and recognition
    - Seven of Wands: Defense and perseverance
    - Eight of Wands: Speed and swift action
    - Nine of Wands: Resilience and boundaries
    - Ten of Wands: Burden and responsibility
    - Page of Wands: Enthusiasm and exploration
    - Knight of Wands: Passion and adventure
    - Queen of Wands: Confidence and charisma
    - King of Wands: Visionary leadership
*/

-- Ace of Wands
UPDATE tarot_cards SET
  meaning_upright = 'Inspiration, creative potential, new opportunities, and the spark of divine fire. The Ace of Wands represents pure creative energy waiting to be channeled into action. This is the moment when a brilliant idea strikes, when passion ignites, and when you feel compelled to bring something new into the world. Like a seed containing the potential for a mighty oak, this card holds the promise of growth, achievement, and manifestation. The Ace of Wands speaks to entrepreneurial ventures, artistic projects, spiritual awakenings, or any endeavor that requires courage and vision. It is the universe handing you a torch and saying "go forth and create." This fiery energy brings enthusiasm, confidence, and the drive to take initiative. When this card appears, seize the moment before the spark fades.',
  meaning_reversed = 'Creative blocks, delays in new projects, lack of direction, or misdirected energy. The spark of inspiration may be present but struggling to take hold, or you may be experiencing false starts and setbacks. This reversal can indicate that you are not ready to move forward, that external obstacles are dampening your enthusiasm, or that your creative fire is burning too hot without proper focus. You might be starting too many projects without finishing any, or feeling uninspired and unmotivated. Sometimes this card reversed suggests impatience—trying to force results before laying proper groundwork. The seed needs time to germinate; rushing the process will not make it grow faster. Examine whether fear is holding you back or if you need to refine your vision before taking action.',
  description = 'A strong hand emerges from swirling clouds, grasping a sturdy wooden wand that stands tall and proud against a dramatic sky. The wand is alive with energy, sprouting fresh green leaves that reach skyward—a powerful symbol of growth, vitality, and untapped potential ready to flourish. In the distance, a winding river cuts through a lush valley dotted with trees and leading toward a majestic castle perched on distant hills, representing the journey from inspiration to manifestation. Mountains frame the horizon, symbolizing the challenges that will be overcome. The sky itself seems to pulse with possibility, painted in warm golds and vibrant blues. Leaves drift down from the wand like blessings falling from heaven, each one a seed of potential waiting to take root. This is the gift of pure creative force—raw, powerful, and demanding to be used.',
  love_meaning = 'New passionate beginnings in love—whether a thrilling new relationship, renewed spark in an existing partnership, or powerful attraction. If single, you may feel magnetic and confident, drawing potential partners with your vitality and enthusiasm. This is an excellent time for first dates, bold romantic gestures, or confessing feelings. If partnered, expect excitement to return to your relationship through spontaneity, adventure, or reignited physical passion. The Ace of Wands brings sexual chemistry and the courage to be vulnerable. However, remember that initial passion must be nurtured to become lasting love. Enjoy the intoxicating beginning but don''t mistake intensity for long-term compatibility.',
  career_meaning = 'A fantastic omen for career matters—new job opportunities, entrepreneurial ventures, creative projects, or promotions. This card often appears when you are considering a career change or starting your own business, indicating that the timing is favorable and your ideas have merit. Your enthusiasm and vision will inspire others and attract support. This is the time to pitch ideas, take initiative, and demonstrate leadership. Creative fields are especially favored—art, writing, design, marketing, entertainment. The Ace of Wands can also represent a breakthrough idea that revolutionizes your work or industry. Trust your instincts and act boldly. Your passion and dedication will overcome obstacles and lead to success.',
  reflection_prompt = 'What creative spark or opportunity is trying to ignite in my life right now? What new beginning am I being called toward? How can I harness this surge of energy and direct it toward meaningful creation? What fears or doubts are preventing me from seizing this moment?'
WHERE name = 'Ace of Wands' AND suit = 'wands';

-- Two of Wands
UPDATE tarot_cards SET
  meaning_upright = 'Planning, future vision, personal power, and bold decision-making. The Two of Wands represents the moment after initial inspiration when you must chart your course and commit to a direction. You have planted your seed (Ace) and now stand surveying the landscape, contemplating which path will lead to your desired destination. This card speaks to ambition, discovery, and the courage to leave your comfort zone in pursuit of greater things. You are no longer content with small victories—your vision has expanded and you crave significance, adventure, and lasting achievement. The Two of Wands asks you to think globally, plan strategically, and trust your inner compass. This is a card of empowered choice, where you hold the world in your hands and decide your fate. Fear and excitement mingle as you prepare to embark on your journey.',
  meaning_reversed = 'Fear of the unknown, poor planning, lack of progress, or indecision. You may have big dreams but find yourself paralyzed by uncertainty, unable to commit to a path forward. This reversal often indicates playing it safe, staying in your comfort zone even though you feel called to something greater. Perhaps you are overwhelmed by options, suffering from analysis paralysis, or lacking the confidence to trust your judgment. Plans may fall apart due to inadequate preparation or external obstacles that weren''t anticipated. Sometimes this card suggests that your ambitions exceed your current capabilities, or that you are not yet ready to take the leap. Alternatively, you might be trapped by others'' expectations, unable to choose the path that truly calls to your heart. Take time to clarify your vision and address the fears holding you back.',
  description = 'A commanding figure stands on the battlements of a fortified castle, one hand resting on a tall wand planted firmly beside them while grasping another, holding a small globe as if contemplating the vast world beyond. They gaze across a landscape of rolling hills and endless horizons, their back to the security of home, facing the unknown with both trepidation and determination. The view stretches far and wide—mountains in the distance, a shimmering sea, fertile valleys waiting to be explored. Red roses and white lilies bloom on the wall, symbols of passion and purity guiding this quest. The figure wears rich robes decorated with salamanders and crosses, representing transformation through fire and spiritual protection on the journey ahead. They have achieved initial success (the castle) but know greater things await beyond familiar walls.',
  love_meaning = 'Decision-making in relationships—choosing between partners, deciding whether to commit, or contemplating the future of your relationship. If single, you may be weighing options or wondering whether to pursue someone who lives far away or requires significant life changes. This card can indicate long-distance relationships or meeting someone while traveling. If partnered, you are planning your shared future together—discussing marriage, moving in together, starting a family, or making other significant commitments. The Two of Wands encourages honest conversation about your visions and values to ensure you are aligned. This is also a time when you may need to balance personal ambitions with relationship needs. Make sure your plans honor both partners.',
  career_meaning = 'Strategic planning, business partnerships, international opportunities, or expansion. You are in a strong position to make important career decisions that will shape your future. This card often appears when considering overseas work, global business ventures, or partnerships that broaden your reach. Your ambition is backed by solid groundwork—you have proven your capabilities and now have the resources to think bigger. Consider collaborations, mergers, or ventures that combine your strengths with others''. The Two of Wands favors entrepreneurs, consultants, and anyone charting their own course. Take time to create detailed plans and contingencies. Success requires both bold vision and practical strategy. Trust your expertise and don''t be afraid to aim high.',
  reflection_prompt = 'What bigger vision am I being called to pursue? What fears are keeping me from leaving my comfort zone? How can I honor both my need for security and my desire for adventure? What would I attempt if I knew I could not fail?'
WHERE name = 'Two of Wands' AND suit = 'wands';

-- Three of Wands
UPDATE tarot_cards SET
  meaning_upright = 'Expansion, foresight, overseas opportunities, and manifestation of long-term plans. The Three of Wands represents the moment when your ships literally come in—when investments of time, energy, and resources begin bearing fruit. You have done the groundwork, taken the risks, and now rewards are on the horizon. This card speaks to international commerce, long-distance ventures, and expanding your sphere of influence beyond familiar territory. Your vision is becoming reality, but success requires patience as you wait for all elements to align. The Three of Wands embodies the entrepreneurial spirit—someone who sees opportunities others miss and has the courage to act on them. Leadership, foresight, and strategic thinking are rewarded. This is a card of momentum building, of watching your plans unfold according to vision, and of preparing to receive abundance.',
  meaning_reversed = 'Delays in plans, obstacles to expansion, lack of foresight, or playing it safe. Your ships may be delayed at sea, encountering storms or unfavorable winds. Opportunities that seemed promising may fall through or take much longer than expected. This reversal can indicate poor planning, failure to consider all variables, or external circumstances beyond your control interfering with progress. You might be frustrated by slow results despite significant effort. Sometimes this card suggests limiting beliefs holding you back—fear of success, fear of failure, or imposter syndrome keeping you from claiming your rightful rewards. Perhaps you are not thinking big enough, refusing to step into larger opportunities out of self-doubt. Alternatively, you may need to reassess your strategy, as current plans may be flawed. Don''t abandon your vision, but be willing to adapt.',
  description = 'A figure stands elevated on a cliff overlooking a vast expanse of water, watching three ships with billowing sails glide toward shore carrying cargo from distant lands. They hold a tall wand firmly planted in the ground while two others stand behind them, forming a gateway to new possibilities. The figure''s stance is confident yet patient—someone who has sent their ventures into the world and now awaits their return. The landscape stretches endlessly, suggesting limitless potential and far-reaching influence. Mountains rise in the distance where earth meets sky, representing both the heights already achieved and further peaks to conquer. The figure wears warm robes of orange and red, colors of creative fire and passionate determination. They have done all they can; now they must trust the winds of fate to deliver their rewards.',
  love_meaning = 'Long-distance relationships, meeting someone while traveling, or relationships expanding to new levels. If single, love may come from unexpected places—perhaps someone from a different culture or country, or someone you meet during travels or through expanded social circles. This card encourages you to broaden your horizons and not limit yourself to familiar options. If partnered, your relationship is entering a phase of growth and expansion—perhaps planning travels together, meeting each other''s extended families, or making long-term commitments. The Three of Wands can also indicate that seeds planted earlier in the relationship are now blossoming. Trust in the foundation you''ve built together and be excited about what''s developing. However, ensure you remain present and patient as things unfold.',
  career_meaning = 'Major career advancement, international business opportunities, or successful expansion of your ventures. This is an excellent card for entrepreneurs, import/export businesses, consultants with multiple clients, or anyone whose work spans geographical boundaries. Your reputation is spreading, and opportunities are flowing in from various sources. Collaborations and partnerships formed earlier are proving fruitful. This card can also indicate promotion to a position with greater scope and influence, or taking your business to the next level through strategic expansion. The Three of Wands rewards those who think globally and plan strategically. Continue to monitor your ventures and adjust as needed, but trust that your efforts will yield results. Success is on the horizon.',
  reflection_prompt = 'Where are my current efforts leading? What investments am I waiting to bear fruit? How can I expand my vision and think bigger about my possibilities? What role does patience play in achieving my long-term goals?'
WHERE name = 'Three of Wands' AND suit = 'wands';

-- Four of Wands
UPDATE tarot_cards SET
  meaning_upright = 'Celebration, harmony, homecoming, community, and joyful milestones. The Four of Wands represents moments of pure happiness—weddings, housewarmings, graduations, reunions, and victories worth celebrating. This card speaks to stability achieved through effort, foundations successfully laid, and the joy of gathering with loved ones to honor accomplishments. After the expansion of the Three, you have created something solid and worth protecting—a home, a relationship, a business, a creative work. The Four of Wands is permission to pause and enjoy what you have built before continuing your journey. It emphasizes the importance of ritual, tradition, and marking life''s passages. This is a time of harmony, gratitude, and feeling genuinely happy and secure. Community support surrounds you, and you feel a deep sense of belonging.',
  meaning_reversed = 'Disrupted celebrations, lack of support, instability at home, or transitions without closure. Plans for gatherings may fall through, or celebrations may be dampened by conflict or absence. This reversal often indicates feeling unwelcome, unsupported, or disconnected from community and family. You might be going through transitions—moving, relationship changes, or shifts in life circumstances—without proper closure or acknowledgment. Perhaps you are comparing your life to others'' highlight reels and feeling that you have nothing to celebrate. Sometimes this card suggests that harmony is superficial, with underlying tensions threatening to surface. Alternatively, you may be so focused on reaching the next goal that you forget to appreciate current blessings. Take time to honor your progress and address what''s creating instability. Seek out supportive community.',
  description = 'Four sturdy wands stand upright forming the corner posts of a festive bower, draped with garlands of flowers, fruits, and autumn leaves—a canopy of abundance and celebration. Two figures in the foreground raise bouquets of blooms in joyful salute, their postures exuberant and free. Behind them, more people dance and celebrate before a castle that represents both security and achievement. The scene radiates warmth, community, and shared happiness. A bridge spans water in the background, symbolizing connections and transitions successfully navigated. The entire image speaks to harvest, homecoming, and the deep satisfaction of building something lasting. This is a moment of pure joy—work has been accomplished, goals achieved, and now it is time to revel in success with those who matter most. The atmosphere is one of safety, support, and collective triumph.',
  love_meaning = 'Weddings, engagements, moving in together, or celebrating relationship milestones. This is one of the most positive cards for love, indicating stable, harmonious, and joyful partnerships. If single, you may be entering a phase where you feel complete and happy in yourself, which attracts healthy relationships. You might also meet someone at a celebration or gathering. If partnered, your relationship is reaching a significant milestone worth celebrating—perhaps getting engaged, married, buying a home together, or simply achieving a new level of harmony and commitment. The Four of Wands blesses unions and emphasizes the importance of celebrating your love publicly and traditionally. Family and friends support your relationship. This is a time of happiness, security, and feeling truly at home with your partner.',
  career_meaning = 'Work anniversaries, project completions, team celebrations, or achieving significant professional milestones. This card indicates successful completion of a phase or project, and it is important to acknowledge this achievement before moving on to the next challenge. You may be receiving recognition from colleagues and superiors, or celebrating as a team. The Four of Wands can also indicate returning to a previous job or location that feels like coming home, or finding your professional "tribe" where you truly belong. Company gatherings, team building events, and collaborative successes are highlighted. This is an excellent time for networking events and professional communities. Enjoy the stability and recognition you have earned. Your contributions are valued and appreciated.',
  reflection_prompt = 'What in my life is worth celebrating right now? How can I create more moments of joy and community? What foundations have I built that provide stability and security? Who are my people, and how can I honor those relationships?'
WHERE name = 'Four of Wands' AND suit = 'wands';

-- Five of Wands
UPDATE tarot_cards SET
  meaning_upright = 'Competition, conflict, diversity of opinion, and productive struggle. The Five of Wands represents the chaos that emerges when multiple strong wills, visions, or approaches clash. This is not malicious combat but rather the friction that occurs when passionate individuals push for different directions. Think brainstorming sessions where everyone talks at once, team sports, competitive markets, or family disagreements where everyone believes they are right. This card acknowledges that conflict is not inherently negative—it can spark innovation, strengthen skills, and clarify what truly matters. The Five of Wands challenges you to hold your ground, defend your ideas, and engage with opposing viewpoints. Growth often requires struggle. This card can indicate feeling overwhelmed by competing demands, but also recognizes that working through differences builds character and resilience. Navigate the chaos with good humor and remember that everyone is fighting their own battle.',
  meaning_reversed = 'Avoiding necessary conflict, suppressing differences, or escalating to harmful competition. When reversed, the Five of Wands suggests that you are either backing down too easily—failing to assert yourself or defend your position—or that competition has turned toxic and destructive. Perhaps you are exhausted by constant battling and ready to find common ground. This reversal can indicate resolution of conflicts, with diverse parties finally agreeing on direction. Alternatively, you might be creating conflict where none truly exists, or fighting battles not worth winning. Sometimes this card suggests internal conflict—battling yourself, sabotaging your own progress, or engaging in negative self-talk. Examine whether current struggles serve your growth or simply drain your energy. Choose your battles wisely.',
  description = 'Five young figures wielding wands engage in what appears to be playful but chaotic combat, their staffs raised high and crossing in the air. No one is actually hurt—this is practice, sport, or spirited debate rather than true battle. Each person wears different colored garments, representing diverse perspectives and approaches. Their expressions show determination and competitive fire, but not genuine malice. The scene captures the confusion and energy of multiple forces pushing in different directions simultaneously. Some figures seem to be working together, others against each other, and it is unclear who is on which side—perhaps because allegiances keep shifting. The background is sparse and neutral, keeping focus on the dynamic interplay of competing wills. This is the necessary friction that tests ideas, strengthens resolve, and ultimately moves everyone forward, even if the path is messy.',
  love_meaning = 'Power struggles, petty arguments, or passionate disagreements in relationships. If single, you may be dealing with multiple suitors or feeling pulled in different directions romantically. Dating may feel competitive or exhausting. This card can indicate that your approach to love conflicts with what you encounter, requiring flexibility. If partnered, expect some bickering or disagreements—not dealbreakers but sources of temporary tension. You and your partner may have different visions for the relationship or struggle with whose needs take priority. The key is to engage with these differences respectfully and with good humor, understanding that some friction is normal and even healthy. Fighting fairly strengthens relationships. However, if every interaction feels like a battle, deeper incompatibilities may exist. Make sure you are teammates, not opponents.',
  career_meaning = 'Competitive work environments, creative differences, team conflicts, or the struggle to stand out in a crowded field. This card often appears in highly competitive industries or when multiple colleagues vie for the same promotion or recognition. You may need to fight for your ideas to be heard or defend your work against criticism. Office politics and interpersonal conflicts can drain energy, but engaging skillfully can also demonstrate your capabilities. The Five of Wands can indicate productive creative tension—brainstorming sessions where ideas clash but ultimately lead to innovation. Don''t be afraid to speak up and assert your expertise. However, choose collaboration over competition when possible. Focus on the shared goal rather than individual glory. The strongest teams harness diverse perspectives.',
  reflection_prompt = 'What am I currently struggling against? Are these conflicts productive or draining? How can I assert myself while remaining open to others'' perspectives? What would happen if I stopped fighting and found common ground instead?'
WHERE name = 'Five of Wands' AND suit = 'wands';

-- Six of Wands
UPDATE tarot_cards SET
  meaning_upright = 'Victory, public recognition, success, and triumphant achievement. The Six of Wands represents the moment when your hard work is acknowledged publicly, when you receive accolades and praise, when you stand victorious after overcoming challenges. This is earned success—not luck, but the result of skill, determination, and perseverance. You have fought through the competition of the Five and emerged as the clear winner. Others look to you with admiration and respect, celebrating your accomplishments. This card speaks to confidence, leadership, and being in the spotlight. You are not merely achieving personal goals but inspiring others through your example. The Six of Wands encourages you to accept recognition graciously, to own your accomplishments without false modesty, and to use your platform to elevate others. This is your moment to shine.',
  meaning_reversed = 'Private victories without recognition, fall from grace, ego inflation, or delayed success. Recognition you expected may not materialize, leaving you feeling overlooked despite your achievements. Perhaps others take credit for your work, or your contributions are undervalued. This reversal can also indicate that you have become too focused on external validation, needing constant praise to feel worthy. Sometimes the Six reversed warns against arrogance—letting success go to your head, becoming boastful or condescending, or alienating others through your ego. You might be comparing yourself to others and feeling inadequate, or experiencing imposter syndrome despite genuine accomplishments. Alternatively, this card can represent the positive choice to celebrate privately, finding satisfaction in the work itself rather than public applause. Remember that true success is internal.',
  description = 'A victorious figure rides a magnificent white horse through streets lined with admirers, their head held high with justified confidence. They carry a tall wand crowned with a laurel wreath—the ancient symbol of victory and achievement—and wear their own laurel crown, marking them as champion. Five other wands held aloft by the crowd create an honor guard celebrating their triumph. The horse steps proudly, and the rider''s posture radiates self-assurance without arrogance. The people gathered show genuine admiration and support, not jealousy or resentment. The scene captures that rare moment when individual excellence benefits the collective, when one person''s victory inspires hope in everyone. This is the homecoming parade, the award ceremony, the moment when efforts are finally acknowledged and celebrated publicly.',
  love_meaning = 'Public recognition of your relationship, receiving approval and support, or feeling confident and attractive. If single, your confidence is magnetic—you shine brightly and others notice. This is an excellent time for dating, as you present your best self. You may receive flattering attention or compete successfully for someone''s affection. If partnered, you and your partner may make your relationship "official" through engagement, marriage, or public declaration. Your relationship is admired by others and may serve as an example or inspiration. The Six of Wands can also indicate that one partner receives recognition or success, which benefits the relationship. Celebrate each other''s victories and let your love be visible. Pride in your partnership strengthens your bond. However, ensure your relationship is solid internally, not just impressive externally.',
  career_meaning = 'Promotion, awards, public recognition, successful presentations, or leadership positions. This is one of the best cards for career success—your work is being acknowledged and celebrated. You may receive a promotion, win an award, successfully pitch a major project, or be recognized as a leader in your field. Colleagues and superiors respect your abilities and accomplishments. This is an excellent time for public speaking, putting yourself forward for opportunities, or accepting leadership roles. Your confidence is well-founded and will attract further success. The Six of Wands can also indicate successfully completing a major project or achieving goals others doubted you could reach. Accept recognition graciously and use your success to mentor others. Remember that leadership is service.',
  reflection_prompt = 'How do I handle success and recognition? Can I accept praise gracefully without false modesty? How can I use my accomplishments to inspire and elevate others? What victory am I currently celebrating or overlooking?'
WHERE name = 'Six of Wands' AND suit = 'wands';

-- Seven of Wands
UPDATE tarot_cards SET
  meaning_upright = 'Defense, challenge, perseverance, and maintaining your position against opposition. The Seven of Wands represents standing your ground when others challenge your success, beliefs, or authority. You have achieved victory (Six) and now must defend what you have won. This card acknowledges that success attracts both admiration and jealousy, and that holding your position requires ongoing effort. You may face competitors, critics, or obstacles testing your resolve. The Seven of Wands calls for courage, determination, and conviction in your path. This is not the time to back down or compromise your values—stand firm in your truth. You have the high ground and the advantage, but maintaining it requires vigilance. This card often appears when you feel outnumbered or overwhelmed by challenges, reminding you that you are stronger than you think and your cause is just.',
  meaning_reversed = 'Exhaustion, giving up, overwhelm, or fighting battles not worth winning. You may be spreading yourself too thin, defending too many fronts, or struggling against forces more powerful than you realized. This reversal suggests that constant defensiveness is draining your energy and preventing forward progress. Perhaps you are making unnecessary enemies by being too aggressive or defensive, or fighting to maintain a position that no longer serves you. Sometimes this card indicates that you need to retreat strategically, conserve energy, and choose which battles matter most. Alternatively, you might be avoiding necessary confrontation, failing to stand up for yourself, or allowing others to take advantage. Examine whether your struggles are productive or if you are fighting out of stubbornness rather than wisdom. It is okay to retreat and regroup.',
  description = 'A determined figure stands alone on elevated ground, wielding a long staff defensively against six other wands being thrust upward from below. Their stance is strong despite being outnumbered—feet planted firmly, expression resolute, ready to defend their position at all costs. The high ground gives them strategic advantage, though the opposition is numerous and persistent. They wear mismatched shoes, suggesting they jumped into this battle quickly without full preparation, yet their commitment is unwavering. The landscape shows them standing on a cliff edge—there is nowhere to retreat, making defense both necessary and courageous. This is the image of someone who has earned their position and will not surrender it easily. They may be tired, they may be outnumbered, but they will not back down. Courage is standing firm when it would be easier to run.',
  love_meaning = 'Defending your relationship against outside interference, standing up for your partner, or protecting your boundaries. If single, you may need to assert your standards and refuse to settle, even when others pressure you or when loneliness tempts compromise. This card can indicate competing for someone''s affection against other suitors. If partnered, you might face disapproval from family or friends, requiring you to defend your choice of partner. Alternatively, you and your partner may need to defend your relationship time and space against work demands, family obligations, or other intrusions. The Seven of Wands can also suggest internal battles—overcoming your own doubts, insecurities, or relationship patterns. Stand firm in your truth. Protect what matters. However, ensure you are fighting for the right reasons and not creating unnecessary conflict.',
  career_meaning = 'Defending your position, facing increased competition, or standing up for your ideas. After the recognition of the Six, you now must prove yourself repeatedly as others challenge your authority or attempt to take your place. This card often appears during performance reviews, competitive projects, or when you must defend your work against criticism. You may feel constantly "on"—pressured to maintain high standards and justify your success. The Seven of Wands requires stamina, confidence, and unwavering belief in your capabilities. This is not the time to doubt yourself. Hold your ground and remember why you earned your position. However, ensure you are not being overly defensive or resistant to valid feedback. Choose which battles matter and don''t exhaust yourself fighting on every front. You have what it takes.',
  reflection_prompt = 'What am I fighting to defend? Is this battle worth my energy? Where do I need to stand firmer in my convictions? How can I maintain my position without becoming exhausted or isolated? When is retreat actually strategic wisdom?'
WHERE name = 'Seven of Wands' AND suit = 'wands';

-- Eight of Wands
UPDATE tarot_cards SET
  meaning_upright = 'Speed, swift action, rapid progress, and sudden movement. The Eight of Wands represents momentum building to a crescendo—events unfolding quickly, messages flying back and forth, travel plans materializing, projects accelerating toward completion. This card is pure forward motion, cutting through obstacles that seemed immovable. After the defensive stance of the Seven, barriers suddenly fall away and everything begins moving at once. Communication flows easily, decisions are made rapidly, and action replaces overthinking. The Eight of Wands often indicates air travel, quick trips, or situations resolving faster than expected. This is the card of "things are happening!" energy—exciting, slightly overwhelming, but ultimately positive. Strike while the iron is hot. The window of opportunity will not stay open indefinitely. This is not the time for hesitation—trust your instincts and move forward with confidence.',
  meaning_reversed = 'Delays, frustration, miscommunication, or resistance to change. Movement you expected grinds to a halt, projects stall, and messages go unanswered. This reversal indicates obstacles blocking your path—bureaucratic red tape, technological failures, missed connections, or external circumstances beyond your control. You may feel impatient and frustrated by slow progress despite your efforts. Sometimes the Eight reversed suggests that you are rushing forward without proper planning, causing chaos and mistakes that then require fixing. Alternatively, you might be resisting necessary change, holding back when you should be moving forward. This card can indicate scattered energy—too many things happening at once without focus or direction. Slow down, reassess your approach, and address what is causing delays. Not all movement is progress.',
  description = 'Eight wands fly through the air like arrows released from a bow, streaking diagonally across a clear blue sky above a peaceful landscape of rolling green hills, a winding river, and distant buildings. The wands travel with purpose and speed, their trajectory certain and their destination inevitable. There are no figures, no obstacles, no hesitation—only pure forward momentum. The scene conveys clarity, direction, and the exhilarating rush of events finally moving after a period of stasis. The wands seem to hum with energy as they slice through air, each one aligned with the others in perfect formation. This is the universe clearing the path and accelerating progress. The landscape below continues its peaceful rhythm, unaware of the swift changes approaching. This card captures the moment when everything suddenly clicks into place and action becomes effortless.',
  love_meaning = 'Quick relationship developments, exciting romantic communications, or sudden progress. If single, you may experience a whirlwind romance that develops rapidly, or finally receive messages from someone you have been waiting to hear from. This card can indicate meeting someone while traveling or through online dating. If partnered, expect an exciting phase where your relationship accelerates—perhaps moving in together, getting engaged, or taking another significant step forward faster than expected. The Eight of Wands brings passionate communication and the removal of obstacles that were preventing connection. However, while speed is thrilling, ensure you are not rushing into commitment before properly assessing compatibility. Enjoy the momentum but maintain awareness. Some things are worth slowing down for.',
  career_meaning = 'Rapid career developments, quick project timelines, business travel, or breakthrough momentum. This card often indicates a busy period where everything happens at once—multiple opportunities, fast-approaching deadlines, extensive communication, and swift decisions required. You may receive job offers, hear back about applications, or finalize deals much faster than expected. Business travel and remote work across time zones are highlighted. The Eight of Wands favors roles requiring quick thinking, adaptability, and excellent communication. This is an excellent time for launching projects, pitching ideas, or making decisive moves. However, with so much happening quickly, ensure you don''t miss important details or overcommit. Stay organized and focused. The momentum is in your favor—use it wisely.',
  reflection_prompt = 'What in my life is finally moving forward? How can I harness this momentum productively? What messages or communications am I waiting for or need to send? Where am I being called to act swiftly rather than hesitate? How do I feel about rapid change?'
WHERE name = 'Eight of Wands' AND suit = 'wands';

-- Nine of Wands
UPDATE tarot_cards SET
  meaning_upright = 'Resilience, persistence, last stand, and defended boundaries. The Nine of Wands represents the warrior who has been through battle—wounded but not defeated, exhausted but still standing, wary but unwilling to quit. You have come so far and overcome so much; now is not the time to give up. This card acknowledges the toll that sustained effort takes—physical exhaustion, emotional drain, the scars of previous battles. Yet despite everything, you maintain your defensive position, ready to face one more challenge if necessary. The Nine of Wands speaks to courage born of experience, the strength that comes from surviving difficulty, and the determination to protect what you have worked so hard to build. You are battle-tested and should trust your instincts about danger. This card often appears during the final, most difficult phase of a challenge—right before breakthrough. Hold the line a little longer.',
  meaning_reversed = 'Exhaustion, paranoia, inability to relax, or crumbling defenses. You may be so wounded and wary from past battles that you see threats everywhere, even where none exist. This reversal suggests burnout, defensiveness that has become excessive, or refusing help because you trust no one. Perhaps you are at your breaking point, unable to endure even one more challenge. The Nine reversed can indicate that your defenses are failing—you can no longer maintain boundaries, fight back, or protect your position. Sometimes this card suggests that it is time to surrender, to ask for help, or to retreat and recover rather than push through. Alternatively, you might be avoiding necessary conflict, failing to defend yourself, or giving up too easily. Examine whether your wariness is protective wisdom or paranoid exhaustion. You cannot pour from an empty cup.',
  description = 'A weathered warrior stands guard, leaning on a staff for support while eight other wands form a protective barrier behind them. They appear wounded—a bandage wraps their head—and exhausted, but their eyes remain alert and vigilant. Their posture suggests someone who has been defending this position for a long time and will continue as long as necessary. The landscape is barren and exposed, offering little shelter or comfort. This is someone standing alone on the wall during a long siege, watching for threats, unwilling to let down their guard. Their expression combines determination with weariness—they know rest will come, but not yet. The wands behind them represent previous victories and overcome obstacles, reminding them of their strength and capability. This is the final test of endurance before triumph.',
  love_meaning = 'Relationship wariness born of past hurt, defensive walls, or persevering through difficult times. If single, you may be guarded and hesitant to open up, protecting your heart after previous disappointments. Trust issues may prevent you from fully engaging with potential partners. This card encourages you to heal wounds before entering new relationships, while also reminding you that vulnerability is necessary for connection. If partnered, you and your partner may be battle-worn from challenges faced together or individually. You might be defending your relationship against external pressures or internal doubts. The Nine of Wands asks you to persevere through difficult times, supporting each other through exhaustion. However, ensure you are not so defensive that you create unnecessary conflict. Sometimes the biggest threat to relationships is bringing past battles into present love.',
  career_meaning = 'Persevering through workplace challenges, defending your position, or nearing the completion of demanding projects. You may feel burned out by sustained pressure, office politics, or the sheer effort required by your role. This card often appears during the final, most difficult phase of a long project when exhaustion tempts you to give up just before the finish line. The Nine of Wands reminds you that you have the strength to complete what you started. You have overcome so much already—don''t quit now. However, this card also warns against burnout and encourages setting boundaries. Defend your work-life balance, learn to say no, and ask for support when needed. Your resilience is admirable but not infinite. Make sure to rest and recover.',
  reflection_prompt = 'What battles have I fought that make me wary now? How can I honor my past while remaining open to the present? Where do I need to maintain my boundaries versus where am I being overly defensive? What gives me strength to persist when exhausted?'
WHERE name = 'Nine of Wands' AND suit = 'wands';

-- Ten of Wands
UPDATE tarot_cards SET
  meaning_upright = 'Burden, responsibility, hard work, and the weight of success. The Ten of Wands represents carrying heavy loads—taking on too much, shouldering all responsibility yourself, or being overburdened by the very success you worked so hard to achieve. You are so close to your destination, but the final stretch is the most difficult. This card acknowledges the cost of ambition—the sacrifices made, the toll taken on mind and body, the stress of maintaining everything you have built. The Ten of Wands can indicate that you refuse to delegate, believing no one else can meet your standards, or that you have taken on commitments beyond your capacity. Yet this card also honors your dedication and work ethic. You keep going because you are responsible, because others depend on you, because quitting is not in your nature. The finish line is just ahead—you can endure a bit more.',
  meaning_reversed = 'Inability to delegate, burnout, collapsed under pressure, or releasing burdens. The Ten reversed often indicates that you have reached your absolute limit—you cannot carry one more thing. The load is too heavy, and something must change. This reversal can represent the healthy choice to put down unnecessary burdens, to delegate tasks, to ask for help, or to walk away from commitments that are destroying you. Sometimes this card suggests that you are avoiding responsibility, refusing to do your share, or giving up too easily when things get difficult. Alternatively, you might be carrying burdens that belong to others—codependent behavior, martyr syndrome, or taking on others'' problems while neglecting your own wellbeing. Examine what you are carrying and why. You are allowed to put down what no longer serves you.',
  description = 'A bent figure struggles forward under the weight of ten heavy wands bundled in their arms, blocking their vision and bowing their back. Their destination—a village with home fires burning—is visible in the near distance, yet seems impossibly far given the burden they carry. Their posture speaks to exhaustion, determination, and the grinding effort of the final stretch. They have come too far to stop now, though every step is agony. The wands obscure their view, suggesting that they can no longer see clearly, focused only on putting one foot in front of the other. No one helps them—they carry this load alone, whether by necessity or by choice. This is the cost of success, the price of achievement, the burden of responsibility. It is also the final test before rest.',
  love_meaning = 'Relationship burdens, taking on too much responsibility, or feeling weighted down by partnership. If single, you may be so overwhelmed by other life responsibilities that you have no energy left for dating or relationships. This card can indicate carrying emotional baggage from past relationships that prevents you from engaging fully in new ones. If partnered, you might feel that you carry most of the relationship burden—handling household tasks, emotional labor, or supporting your partner without reciprocal support. The Ten of Wands can also represent the stress that external pressures place on your relationship. Work, family obligations, or life circumstances may leave little time or energy for connection. This card urges honest conversation about balance and support. Relationships require two people carrying the load together. It is okay to ask for help.',
  career_meaning = 'Work overwhelm, too many responsibilities, or nearing burnout. You may have taken on too much, said yes to too many projects, or found that success brings more work rather than more freedom. This card often appears during peak busy seasons or when you are juggling multiple major responsibilities simultaneously. The Ten of Wands acknowledges that sometimes heavy workload is temporary—a big project with a deadline, a critical business phase, or a time when all hands must be on deck. However, if this is your constant state, something must change. Consider delegation, automation, or refusing new commitments. The Ten can also indicate that you are approaching completion of a major project—push through the final difficult phase, then rest and reassess. You are stronger than you realize, but even strength has limits.',
  reflection_prompt = 'What burdens am I carrying that I could put down? Why do I feel I must do everything myself? Where do I need to delegate, ask for help, or simply say no? What would my life look like if I released what no longer serves me? How close am I to my goal?'
WHERE name = 'Ten of Wands' AND suit = 'wands';

-- Page of Wands
UPDATE tarot_cards SET
  meaning_upright = 'Enthusiasm, exploration, freedom, discovery, and passionate curiosity. The Page of Wands represents youthful energy, creative sparks, and the excitement of new adventures. This is the messenger bringing news of opportunities, the free spirit setting off to explore the world, the artist filled with fresh inspiration. Pages embody the pure essence of their suit—fire in this case—expressing as passionate enthusiasm, boldness, and the courage to try new things. The Page of Wands is eternally optimistic, seeing possibility everywhere and unafraid of failure. This card often indicates a person (young in spirit if not age) who inspires through their enthusiasm, or represents your own inner child eager to play, create, and explore. News arriving may open exciting new directions. The Page encourages you to approach life with wonder, to take creative risks, and to follow your curiosity wherever it leads.',
  meaning_reversed = 'Lack of direction, scattered energy, delays in plans, or immaturity. The reversed Page may be all talk and no action—full of big ideas that never manifest, or starting projects with enthusiasm only to abandon them when they require sustained effort. This reversal can indicate someone unreliable, prone to exaggeration, or whose passion burns hot then quickly fades. You might be feeling directionless, unsure which of many interests to pursue, or frustrated by lack of progress despite excitement. Sometimes the Page reversed suggests immaturity—acting impulsively, seeking attention, or having tantrums when things don''t go your way. Alternatively, you may be stifling your creative impulses, playing it safe, or letting others'' skepticism dim your enthusiasm. Examine whether your fire needs grounding and discipline, or if it needs permission to burn freely.',
  description = 'A young figure stands in desert landscape, holding a tall wand and gazing at it with fascinated intensity as small flames or sprouts emerge from its tip—a sign of life and potential from dead wood. They wear a tunic decorated with salamanders, mythical creatures that represent transformation through fire, passion made manifest. Their posture is one of excited contemplation—they have received an important message or discovered something fascinating and are determining what to do with it. Three pyramids rise in the distant background, suggesting ancient mysteries waiting to be explored. The Page''s stance is dynamic, ready to leap into action at any moment. This is someone at the very beginning of their journey, filled with enthusiasm and wonder, unencumbered by doubt or cynicism. The world is new and anything seems possible.',
  love_meaning = 'Exciting new romantic interests, playful flirtation, or passionate new beginnings. If single, the Page brings fun, adventurous energy to your love life—enjoy casual dating, flirtation, and the thrill of new connections without pressure for immediate commitment. You may meet someone spontaneous and exciting, or receive messages from someone expressing interest. This card can represent a younger partner or someone young in spirit. If partnered, the Page brings playfulness back to your relationship—plan adventures together, try new experiences, or simply bring more spontaneity and fun to your connection. However, Pages lack maturity and depth—enjoy the excitement but don''t expect deep commitment or emotional sophistication yet. This is the beginning of the story, not its conclusion.',
  career_meaning = 'Exciting career news, new projects, creative opportunities, or apprenticeships. The Page often represents messages about work—job offers, project approvals, or information that opens new directions. This is an excellent card for creative fields, entrepreneurship, or any work requiring passion and innovation. You may be starting a new position, learning new skills, or exploring career options. The Page encourages you to approach work with enthusiasm and curiosity, to take creative risks, and to share your ideas boldly. This can also represent a younger colleague or employee bringing fresh energy to your team, or indicate that you are the enthusiastic newcomer. However, remember that Pages are still learning—be willing to accept guidance, remain coachable, and balance enthusiasm with discipline. Passion without skill needs development.',
  reflection_prompt = 'What sparks my enthusiasm and excitement right now? Where do I need more playfulness and spontaneity in my life? What would I explore if I gave myself permission to be a beginner? What message or opportunity is trying to reach me?'
WHERE name = 'Page of Wands' AND suit = 'wands';

-- Knight of Wands
UPDATE tarot_cards SET
  meaning_upright = 'Action, adventure, passion, impulsiveness, and bold pursuit. The Knight of Wands represents pure fire in motion—someone who charges forward fearlessly, embracing adventure and risk. This is the archetype of the hero on a quest, the adventurer seeking new experiences, the passionate lover pursuing their heart''s desire without hesitation. Knights represent the suit energy in its most active, dynamic form. The Knight of Wands is charismatic, confident, and utterly compelling—people are drawn to their energy and inspired by their courage. This card encourages bold action, taking risks, and following your passion wherever it leads. The Knight reminds you that life is an adventure meant to be lived fully. However, this card also warns of impulsiveness—the tendency to act without thinking, to burn bridges, to move so fast that important details are missed. Channel this powerful energy wisely.',
  meaning_reversed = 'Recklessness, impatience, scattered energy, or burnout. The Knight reversed charges forward without looking, creating chaos and leaving destruction in their wake. This reversal can indicate someone who is all flash and no substance—talks big but doesn''t follow through, makes grand gestures but lacks consistency. You might be acting impulsively, making decisions in the heat of passion that you later regret, or pursuing multiple directions without committing to any. Sometimes this card represents burnout from moving too fast for too long—your fire has consumed all fuel. The Knight reversed can be domineering, aggressive, or prone to angry outbursts. Alternatively, you may be stuck in analysis paralysis, afraid to take the leap, or have lost your passion and drive entirely. Examine whether you need to slow down and gain focus, or whether you need to reignite your fire and take action.',
  description = 'A knight in shining armor emblazoned with salamanders rides a rearing horse through a desert landscape, wand held high like a lance or torch. The horse stands on its hind legs, expressing the same spirited energy as its rider—both are ready to charge forward at a moment''s notice. The knight''s posture radiates confidence and power, their gaze fixed on the distant horizon where adventure awaits. Their armor glints in the sun, both protective and decorative. Flames seem to dance around them, or perhaps it is heat shimmer from the desert—this is someone who brings the fire wherever they go. The pyramids in the background suggest quests toward ancient mysteries and distant lands. This is motion incarnate, passion personified, the warrior poet riding toward destiny without doubt or hesitation.',
  love_meaning = 'Passionate, whirlwind romance, intense attraction, or pursuit of love. If single, the Knight of Wands brings exciting romantic energy—you may meet someone charismatic and adventurous, or embody this energy yourself, pursuing what you desire boldly. Expect intense chemistry and thrilling dates. This card can represent the "sweep you off your feet" experience—dramatic romantic gestures, passionate declarations, exciting adventures together. If partnered, your relationship enters an exciting, passionate phase—rekindle the spark through spontaneity and adventure. However, the Knight''s fire burns hot but can also burn out quickly. While passion is intoxicating, assess whether there is substance beneath the excitement. Knights love the chase but may lose interest once the challenge is won. Enjoy the intensity but keep your eyes open.',
  career_meaning = 'Bold career moves, entrepreneurial ventures, passionate projects, or rapid advancement. The Knight of Wands brings dynamic, action-oriented energy to work—this is an excellent time to take risks, pitch ambitious ideas, or make bold moves in your career. You may feel compelled to quit your job and start your own business, to pursue a passion project, or to advocate strongly for your vision. This card favors careers requiring courage, charisma, and the ability to inspire others—sales, entrepreneurship, athletics, entertainment, emergency services. The Knight can also represent a passionate, dynamic colleague or boss who shakes things up. Act decisively but not recklessly. Balance passion with planning. Your enthusiasm will attract opportunities, but follow-through matters as much as bold starts.',
  reflection_prompt = 'Where do I need to act boldly and courageously? What adventures am I being called toward? How can I channel my passion productively without burning out? Where might I be acting impulsively rather than wisely? What would I do if I knew I couldn''t fail?'
WHERE name = 'Knight of Wands' AND suit = 'wands';

-- Queen of Wands
UPDATE tarot_cards SET
  meaning_upright = 'Confidence, determination, charisma, independence, and radiant leadership. The Queen of Wands is fire energy fully matured and mastered—someone who knows themselves completely, stands in their power unapologetically, and inspires others through their authentic presence. She is the confident leader, the magnetic entrepreneur, the woman who commands a room simply by entering it. The Queen combines passion with wisdom, courage with compassion, independence with connection. She is fiercely protective of those she loves, generous with her support, and unwilling to tolerate disrespect. This card speaks to self-assurance that comes from within, not from external validation. The Queen of Wands encourages you to own your power, express yourself boldly, and lead from the heart. She reminds you that true strength is magnetic, not domineering, and that confidence attracts abundance.',
  meaning_reversed = 'Jealousy, manipulation, self-doubt, or misuse of power. The Queen reversed may be using her considerable power destructively—manipulating others, lashing out when threatened, or demanding the spotlight at all costs. This reversal can indicate someone who appears confident but is actually deeply insecure, controlling others to feel powerful. You might be struggling with low self-esteem, second-guessing yourself, or dimming your light to avoid threatening others. Sometimes this card suggests that you are being demanding, jealous, or vengeful—your fire has become destructive rather than creative. Alternatively, you might be dealing with someone who embodies these negative qualities. The Queen reversed can also indicate burnout—having given so much to others that your own fire has dimmed. Reconnect with your authentic power and remember that true queens lift others up.',
  description = 'A regal queen sits confidently upon her throne, holding a tall wand in one hand and a sunflower—symbol of joy, vitality, and turning toward the light—in the other. A black cat sits at her feet, representing both her mystical connection and her fierce independence. Her throne is carved with lions, symbols of courage and noble strength, and decorated with sunflowers. She wears golden robes that seem to glow with inner fire, and her expression radiates self-assurance and warmth. Behind her, the landscape is fertile and welcoming, showing that her leadership creates abundance for all. Her posture is open and commanding—she has nothing to hide and nothing to fear. This is someone completely comfortable in their own skin, who has integrated all aspects of themselves and now shines brightly without apology. She is both queen and warrior, nurturer and leader.',
  love_meaning = 'Confident, independent partnership, passionate love, or magnetic attraction. If single, embody the Queen''s energy—be fully yourself, unapologetically authentic, and confident in your worth. This attracts partners who can match your fire and appreciate your strength. The Queen doesn''t settle or chase—she knows her value and waits for those worthy of her time. If partnered, this card indicates a relationship between equals where both partners maintain independence while choosing connection. The Queen brings passion, loyalty, and fierce protection to her relationships but refuses to lose herself in partnership. This card can represent a charismatic, confident partner or encourage you to be this energy yourself. However, ensure your strength doesn''t become domineering. The healthiest relationships have two queens or two kings, not a ruler and subject.',
  career_meaning = 'Leadership roles, entrepreneurship, commanding presence, or inspiring others. The Queen of Wands is excellent for career matters—she represents mastery in your field, natural leadership, and the ability to motivate and inspire teams. This card favors positions requiring charisma, confidence, and the ability to command respect—executive roles, entrepreneurship, public speaking, entertainment, creative direction. You are being called to step fully into your power at work, to share your vision boldly, and to lead with both strength and warmth. The Queen can also represent a mentor, boss, or colleague who embodies these qualities and can teach you much. Trust your expertise, own your accomplishments, and don''t be afraid to take center stage. Your confidence and passion are your greatest professional assets.',
  reflection_prompt = 'How fully am I standing in my power? Where do I need to be more confident and unapologetic? How can I lead with both strength and warmth? What would I do if I truly believed in my own magnificence? Where am I dimming my light to make others comfortable?'
WHERE name = 'Queen of Wands' AND suit = 'wands';

-- King of Wands
UPDATE tarot_cards SET
  meaning_upright = 'Visionary leadership, entrepreneurial success, natural authority, and inspired action. The King of Wands represents fire energy at its most mature, balanced, and effective—the natural leader who inspires through example, the visionary entrepreneur who builds empires, the mentor who elevates everyone around them. He has mastered the lessons of his entire suit journey, combining the Ace''s creative spark with the deliberate planning of the Two, the foresight of the Three, the stability of the Four, the competitive edge of the Five, the confidence of the Six, the defensive capability of the Seven, the momentum of the Eight, the resilience of the Nine, and the dedication of the Ten. The King is both warrior and diplomat, dreamer and pragmatist, commanding and warm. He leads with honor, inspires with vision, and creates lasting legacies. This card calls you to step fully into leadership, to share your vision boldly, and to build something meaningful.',
  meaning_reversed = 'Tyranny, impulsiveness, arrogance, or abuse of power. The King reversed uses his considerable power destructively—dominating rather than leading, demanding rather than inspiring, burning bridges rather than building connections. This reversal can indicate someone who is all ego and no substance, whose leadership style is based on fear rather than respect. You might be acting impulsively, making rash decisions without considering consequences, or using your position to serve yourself rather than others. Sometimes this card suggests that you are avoiding leadership responsibilities, refusing to step up when needed, or undermining authority figures. The King reversed can be ruthless, vengeful, or prone to explosive anger. Alternatively, you might be dealing with a toxic leader. True leadership serves the greater good and empowers others.',
  description = 'A commanding king sits upon his throne, wand held like a scepter, radiating authority and power. His throne is carved with lions and salamanders—symbols of courage and transformation through fire—and his robes are vibrant orange and gold, the colors of flame and sun. Behind him, the landscape is both fertile and wild, showing that his leadership creates conditions for growth while honoring natural forces. A small salamander sits at his feet, representing the perpetual flame of inspiration and transformation. The king''s expression combines confidence with wisdom—someone who has earned their authority through experience and wields it with both strength and grace. His posture is commanding but not aggressive; he does not need to prove his power because it is evident. This is the benevolent ruler, the visionary entrepreneur, the honored elder—someone whose fire has been honed into focused, sustainable brilliance.',
  love_meaning = 'Passionate, loyal partnership with a natural leader, or embodying this energy yourself. If single, you may be attracted to or attract someone charismatic, confident, and successful—a natural leader with vision and passion. The King is deeply loyal once committed but needs a partner who can match their intensity and won''t be intimidated by their strength. If partnered, your relationship is characterized by mutual respect, shared vision, and passionate commitment. The King brings stability, protection, and unwavering loyalty. However, ensure the relationship has balance—the King can be domineering if unchecked. The healthiest partnerships have two strong individuals choosing each other, not a leader and follower. This card encourages you to bring your full, powerful self to relationships rather than diminishing to appear less threatening.',
  career_meaning = 'Executive leadership, successful entrepreneurship, mastery in your field, or visionary projects. The King of Wands is one of the best cards for career success—representing senior leadership positions, successful business ownership, or being recognized as an expert and authority in your industry. You have the vision, skills, experience, and charisma to lead major initiatives and inspire teams. This is an excellent time to launch ventures, pursue executive roles, or mentor others. The King favors careers in business, entrepreneurship, consulting, executive leadership, politics, or any field where vision and leadership create impact. Your natural authority will attract opportunities. Lead with honor and generosity. Remember that great leaders create more leaders, not followers. Your legacy will be measured by those you elevate.',
  reflection_prompt = 'What vision am I being called to lead? How can I use my power and influence to serve the greater good? What kind of legacy do I want to leave? Where do I need to step more fully into my authority? How can I inspire others through my example?'
WHERE name = 'King of Wands' AND suit = 'wands';
